#!/bin/bash -l
#SBATCH -D /ptmp/bturo/subtomo/sg_classification_dn_mr1_c1/
#SBATCH -e err_sg_classification_dn_mr1_c1
#SBATCH -o log_sg_classification_dn_mr1_c1
#SBATCH --job-name sg_classification_dn_mr1_c1
#SBATCH --nodes=10
#SBATCH --ntasks-per-node=40
#
#SBATCH --mail-type=ALL
#SBATCH --mail-user=beturono@biophys.mpg.de
#SBATCH --mem=180GB
#SBATCH --time=16:00:00
module purge

module load gcc/10 openmpi/4
module load matlab/R2021bU2
export STOPGAPHOME=/u/bturo/STOPGAP/exec/
echo ${STOPGAPHOME}

export OMP_NUM_THREADS=$SLURM_CPUS_PER_TASK
# For pinning threads correctly:
export OMP_PLACES=cores

srun /u/bturo/STOPGAP/exec//bin/stopgap_mpi_slurm.sh /ptmp/bturo/subtomo/sg_classification_dn_mr1_c1/ subtomo_param.star $SLURM_NTASKS
